# Generated by Django 5.2.4 on 2025-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
